name: Markus Raivio
favicon: null
layout_spectrum: 0.5893617
typography_spectrum: 0.34859
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: >-
  Työnohjaaja,työyhteisön kehittäjä, Propellipäiden pääsihteeri, muusikko,
  äänituottaja
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F0E7D8'
    - '#140A0B'
    - '#C3A98E'
    - '#C72415'
    - '#4A4A52'
  brandStrength: 0.4234042
  lightness: 0.6191489
  saturation: 0.7914894
  rhythmicContrast: 0.8425532
purpose: []
