typography_spectrum: 0.052496701246127486
content_rating:
  adult: false
color:
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  brandStrength: 0.6329950888175517
  lightness: 0.6500930227339268
  saturation: 0.21479279291816056
  rhythmicContrast: 0.7112036519683897
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8507392907049507
analytics:
  google: null
  facebook: null
  twitter: null
logo: null
name: Markus Raivio
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: >-
  Työnohjaaja,työyhteisön kehittäjä, Propellipäiden pääsihteeri, muusikko,
  äänituottaja
purpose: []
