collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.05957447
color:
  saturation: 0.7914894
  brandStrength: 0.4234042
  lightness: 0.6191489
  brandColors:
    - '#F0E7D8'
    - '#140A0B'
    - '#C3A98E'
    - '#C72415'
    - '#4A4A52'
  rhythmicContrast: 0.8425532
layout_spectrum: 0.5893617
name: Markus Raivio
